# Code for NY crime data processing
# 1. API interface
Last modified: Oct. 1, 2021

## 1.1 Get data by selected date

### Sample: Get year 2018-2020 data

In [3]:
# make sure to install these packages before running:
# pip install sodapy
import pandas as pd
from sodapy import Socrata

# Access NY Open Data API
client = Socrata("data.cityofnewyork.us",
                  "SS1FLB8GKDDdNcRMJwXFNS0Wr",
                  username="mk3268@drexel.edu",
                  password="Mact98xz!")

results = client.get("qgea-i56i", limit=1500000,  
    where="cmplnt_fr_dt >= '2018-01-01' and cmplnt_fr_dt <= '2020-12-31'")

# Convert to pandas DataFrame
results_year_2018 = pd.DataFrame.from_records(results)
results_year_2018

,cmplnt_num,cmplnt_fr_dt,cmplnt_fr_tm,cmplnt_to_dt,cmplnt_to_tm,addr_pct_cd,rpt_dt,ky_cd,ofns_desc,pd_cd,...,lat_lon,patrol_boro,vic_age_group,vic_race,vic_sex,housing_psa,hadevelopt,parks_nm,transit_district,station_name
0,947161850,2018-01-01T00:00:00.000,08:00:00,2019-07-31T00:00:00.000,08:00:00,10,2019-12-27T00:00:00.000,109,GRAND LARCENY,407.0,...,"{'latitude': '40.74283378800004', 'longitude':...",PATROL BORO MAN SOUTH,UNKNOWN,UNKNOWN,D,NaN,NaN,NaN,NaN,NaN
1,963870686,2018-01-01T00:00:00.000,00:01:00,2019-10-10T00:00:00.000,23:59:00,103,2019-12-03T00:00:00.000,109,GRAND LARCENY,432.0,...,"{'latitude': '40.71271350400008', 'longitude':...",PATROL BORO QUEENS SOUTH,18-24,BLACK,M,NaN,NaN,NaN,NaN,NaN
2,923975917,2018-01-01T00:00:00.000,07:00:00,2019-11-30T00:00:00.000,14:00:00,112,2019-11-30T00:00:00.000,121,CRIMINAL MISCHIEF & RELATED OF,268.0,...,"{'latitude': '40.730041019000055', 'longitude'...",PATROL BORO QUEENS NORTH,25-44,WHITE,F,NaN,NaN,NaN,NaN,NaN
3,553803536,2018-01-01T00:00:00.000,00:01:00,2018-12-31T00:00:00.000,23:29:00,5,2019-11-29T00:00:00.000,233,SEX CRIMES,175.0,...,"{'latitude': '40.716195914000025', 'longitude'...",PATROL BORO MAN SOUTH,<18,BLACK,F,NaN,NaN,NaN,NaN,NaN
4,994797810,2018-01-01T00:00:00.000,12:00:00,NaN,NaN,77,2019-10-20T00:00:00.000,233,SEX CRIMES,170.0,...,"{'latitude': '40.67458330800008', 'longitude':...",PATROL BORO BKLYN NORTH,<18,BLACK,M,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1324334,165691435,2020-12-31T00:00:00.000,20:40:00,2020-12-31T00:00:00.000,20:50:00,81,2020-12-31T00:00:00.000,118,DANGEROUS WEAPONS,793,...,"{'latitude': '40.679739379000075', 'longitude'...",PATROL BORO BKLYN NORTH,UNKNOWN,UNKNOWN,E,NaN,NaN,NaN,NaN,NaN
1324335,408014308,2020-12-31T00:00:00.000,15:00:00,2020-12-31T00:00:00.000,16:15:00,9,2020-12-31T00:00:00.000,341,PETIT LARCENY,343,...,"{'latitude': '40.72380251300007', 'longitude':...",PATROL BORO MAN SOUTH,45-64,WHITE HISPANIC,M,14115,LOWER EAST SIDE REHAB (GROUP 5),NaN,NaN,NaN
1324336,152189917,2020-12-31T00:00:00.000,21:30:00,2020-12-31T00:00:00.000,21:30:00,20,2020-12-31T00:00:00.000,109,GRAND LARCENY,405,...,"{'latitude': '40.782076545000045', 'longitude'...",PATROL BORO MAN NORTH,25-44,WHITE HISPANIC,F,NaN,NaN,NaN,NaN,NaN
1324337,819066061,2020-12-31T00:00:00.000,20:22:00,2020-12-31T00:00:00.000,20:29:00,75,2020-12-31T00:00:00.000,118,DANGEROUS WEAPONS,792,...,"{'latitude': '40.66934487900005', 'longitude':...",PATROL BORO BKLYN NORTH,UNKNOWN,UNKNOWN,E,NaN,NaN,NaN,NaN,NaN
1324338,675684827,2020-12-31T00:00:00.000,00:42:00,NaN,NaN,44,2020-12-31T00:00:00.000,105,ROBBERY,399,...,"{'latitude': '40.837978220000025', 'longitude'...",PATROL BORO BRONX,25-44,WHITE HISPANIC,M,NaN,NaN,NaN,NaN,NaN

In [4]:
### Save to CSV file (write to a file)
results_year_2018.to_csv("ny_2018-2020.csv", index = False)

## 1.2 Attribute selection

In [4]:
# make sure to install these packages before running:
# pip install sodapy
import pandas as pd
from sodapy import Socrata

# Access NY Open Data API
client = Socrata("data.cityofnewyork.us",
                  "SS1FLB8GKDDdNcRMJwXFNS0Wr",
                  username="mk3268@drexel.edu",
                  password="Mact98xz!")

results = client.get("qgea-i56i", limit=1500000,  
    where="cmplnt_fr_dt >= '2018-01-01' and cmplnt_fr_dt <= '2018-01-07'",
    select = "cmplnt_num, cmplnt_fr_dt, cmplnt_fr_tm, law_cat_cd, ofns_desc, \
    loc_of_occur_desc, latitude, longitude, susp_age_group, susp_race, susp_sex, \
    vic_age_group, vic_race, vic_sex")
# Convert to pandas DataFrame
results_selct = pd.DataFrame.from_records(results)
results_selct

,cmplnt_num,cmplnt_fr_dt,cmplnt_fr_tm,law_cat_cd,ofns_desc,loc_of_occur_desc,latitude,longitude,susp_age_group,susp_race,susp_sex,vic_age_group,vic_race,vic_sex
0,947161850,2018-01-01T00:00:00.000,08:00:00,FELONY,GRAND LARCENY,INSIDE,40.74283378800004,-73.99842802399996,25-44,BLACK,F,UNKNOWN,UNKNOWN,D
1,963870686,2018-01-01T00:00:00.000,00:01:00,FELONY,GRAND LARCENY,INSIDE,40.71271350400008,-73.76993053999998,UNKNOWN,UNKNOWN,U,18-24,BLACK,M
2,923975917,2018-01-01T00:00:00.000,07:00:00,FELONY,CRIMINAL MISCHIEF & RELATED OF,INSIDE,40.730041019000055,-73.851655227,NaN,NaN,NaN,25-44,WHITE,F
3,553803536,2018-01-01T00:00:00.000,00:01:00,MISDEMEANOR,SEX CRIMES,INSIDE,40.716195914000025,-73.99749074599998,UNKNOWN,UNKNOWN,U,<18,BLACK,F
4,994797810,2018-01-01T00:00:00.000,12:00:00,MISDEMEANOR,SEX CRIMES,INSIDE,40.67458330800008,-73.93022154099998,18-24,UNKNOWN,F,<18,BLACK,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8046,774805854,2018-01-07T00:00:00.000,19:10:00,FELONY,GRAND LARCENY OF MOTOR VEHICLE,FRONT OF,40.60635878800008,-73.93006955999994,NaN,NaN,NaN,45-64,WHITE,M
8047,354981956,2018-01-07T00:00:00.000,18:00:00,MISDEMEANOR,OFF. AGNST PUB ORD SENSBLTY &,INSIDE,40.57978019500007,-73.99842465499995,25-44,BLACK,M,25-44,BLACK,F
8048,548498111,2018-01-07T00:00:00.000,03:00:00,MISDEMEANOR,OFF. AGNST PUB ORD SENSBLTY &,INSIDE,40.75673732900003,-73.94103624999997,25-44,BLACK,M,25-44,BLACK,F
8049,330883634,2018-01-07T00:00:00.000,21:50:00,FELONY,DANGEROUS WEAPONS,NaN,40.85688294400006,-73.88770270599997,25-44,BLACK,M,UNKNOWN,UNKNOWN,E
8050,480203632,2018-01-07T00:00:00.000,21:40:00,FELONY,FELONY ASSAULT,INSIDE,40.80653810100006,-73.918910596,45-64,WHITE HISPANIC,F,25-44,WHITE HISPANIC,F

In [6]:
# make sure to install these packages before running:
# pip install sodapy
import pandas as pd
from sodapy import Socrata

# Access NY Open Data API
client = Socrata("data.cityofnewyork.us",
                  "SS1FLB8GKDDdNcRMJwXFNS0Wr",
                  username="mk3268@drexel.edu",
                  password="Mact98xz!")

results = client.get("qgea-i56i", limit=1000000,  
    where="cmplnt_fr_dt >= '2017-01-01' and cmplnt_fr_dt <= '2020-12-31'")

# Convert to pandas DataFrame
results_year_2018 = pd.DataFrame.from_records(results)
results_year_2018

,cmplnt_num,cmplnt_fr_dt,cmplnt_fr_tm,cmplnt_to_dt,cmplnt_to_tm,addr_pct_cd,rpt_dt,ky_cd,ofns_desc,pd_cd,...,lat_lon,patrol_boro,vic_age_group,vic_race,vic_sex,hadevelopt,housing_psa,parks_nm,transit_district,station_name
0,216044876,2017-01-01T00:00:00.000,11:00:00,2018-08-20T00:00:00.000,12:00:00,109,2019-12-31T00:00:00.000,116,SEX CRIMES,179.0,...,"{'latitude': '40.76233421800004', 'longitude':...",PATROL BORO QUEENS NORTH,<18,ASIAN / PACIFIC ISLANDER,F,NaN,NaN,NaN,NaN,NaN
1,112025807,2017-01-01T00:00:00.000,09:00:00,2019-09-01T00:00:00.000,09:00:00,13,2019-12-06T00:00:00.000,233,SEX CRIMES,175.0,...,"{'latitude': '40.736698070000045', 'longitude'...",PATROL BORO MAN SOUTH,45-64,WHITE HISPANIC,M,NaN,NaN,NaN,NaN,NaN
2,669902330,2017-01-01T00:00:00.000,00:01:00,2017-12-31T00:00:00.000,23:59:00,114,2019-11-26T00:00:00.000,233,SEX CRIMES,175.0,...,"{'latitude': '40.76930608700008', 'longitude':...",PATROL BORO QUEENS NORTH,<18,BLACK,F,NaN,NaN,NaN,NaN,NaN
3,579530319,2017-01-01T00:00:00.000,00:00:00,2019-12-01T00:00:00.000,00:00:00,71,2019-11-30T00:00:00.000,112,THEFT-FRAUD,739.0,...,"{'latitude': '40.66502269100005', 'longitude':...",PATROL BORO BKLYN SOUTH,25-44,BLACK,M,NaN,NaN,NaN,NaN,NaN
4,232211816,2017-01-01T00:00:00.000,00:01:00,2017-12-31T00:00:00.000,23:00:00,61,2019-11-26T00:00:00.000,112,THEFT-FRAUD,739.0,...,"{'latitude': '40.607011439000075', 'longitude'...",PATROL BORO BKLYN SOUTH,25-44,ASIAN / PACIFIC ISLANDER,M,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,171093637,2019-03-02T00:00:00.000,01:30:00,2019-03-02T00:00:00.000,01:35:00,61,2019-03-02T00:00:00.000,344,ASSAULT 3 & RELATED OFFENSES,101.0,...,"{'latitude': '40.58395556300008', 'longitude':...",PATROL BORO BKLYN SOUTH,18-24,WHITE,M,NaN,NaN,NaN,NaN,NaN
999996,626329761,2019-03-02T00:00:00.000,21:28:00,2019-03-02T00:00:00.000,21:57:00,24,2019-03-03T00:00:00.000,105,ROBBERY,396.0,...,"{'latitude': '40.792461167000056', 'longitude'...",PATROL BORO MAN NORTH,UNKNOWN,UNKNOWN,D,NaN,NaN,NaN,NaN,NaN
999997,280309300,2019-03-02T00:00:00.000,11:53:00,2019-03-02T00:00:00.000,13:00:00,84,2019-03-02T00:00:00.000,341,PETIT LARCENY,333.0,...,"{'latitude': '40.691011529000036', 'longitude'...",PATROL BORO BKLYN NORTH,UNKNOWN,UNKNOWN,D,NaN,NaN,NaN,NaN,NaN
999998,812193412,2019-03-02T00:00:00.000,07:39:00,2019-03-02T00:00:00.000,07:45:00,19,2019-03-02T00:00:00.000,341,PETIT LARCENY,333.0,...,"{'latitude': '40.77641236200003', 'longitude':...",PATROL BORO MAN NORTH,UNKNOWN,UNKNOWN,D,NaN,NaN,NaN,NaN,NaN
999999,314149792,2019-03-02T00:00:00.000,14:30:00,2019-03-03T00:00:00.000,09:30:00,109,2019-03-03T00:00:00.000,341,PETIT LARCENY,313.0,...,"{'latitude': '40.788338604000046', 'longitude'...",PATROL BORO QUEENS NORTH,25-44,BLACK,F,NaN,NaN,NaN,NaN,NaN